### PR TITLE
chore: version upgrade to NET Standard 2.1 

### PR DESCRIPTION
**Pull request by Rishabh-V**
Version Updates for only ASP.NET Core project. Templates are not updated.

### CODE REVIEW

**Review by jskeet — APPROVED** [review]

**Comment by jskeet** [comment]
Given that you've updated the package version numbers as well, are you going to do a release?

**Comment by Rishabh-V** [comment]
> Given that you've updated the package version numbers as well, are you going to do a release?

I am happy to do it under your guidance :) I don't have authorization to merge. 
The repo doesn't seem to have the release pipeline setup, so would we need to manually do the dotnet pack and upload to nuget. Given, I haven't done this so docs or guidance on this would surely help.

**Comment by jskeet** [comment]
Okay, I definitely don't have time to go through those steps or guide you through them today. Please could you change this PR so that it *just* updates the dependencies without looking like it would then do a release? I'll give you write permission now.

**Comment by Rishabh-V** [comment]
> Okay, I definitely don't have time to go through those steps or guide you through them today. Please could you change this PR so that it _just_ updates the dependencies without looking like it would then do a release? I'll give you write permission now.

Sure Jon.

**Review by jskeet — APPROVED** [review]
Thanks - you should be able to merge this yourself now.

**Pull request merged**
